### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fabio-t** [fabioticconi/DirtyLittlePhysics#2]
- [ ] decide on a general way of solving collisions, and fix the relevant API
- [ ] tests
- [ ] documentation
- [ ] easy: re-factor this into a proper maven project
- [ ] maybe rename to dirty-little-physics?

**Comment by fabioticconi** [comment]
good resource for spring constraint: https://dl.dropboxusercontent.com/u/3894132/Stable%20springs%200.7.0.pdf
